In [ ]:
#Q1
import numpy as np
a=np.array([1,2,3,4,5])
a1=a+2
print(a1)
a2=a*3
print(a2)
a3=a/2
print(a3)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [ ]:
#Q2
arr=np.array([1,2,3,6,4,5])
print(arr[::-1])
def most_freq(arr):
  unique,counts=np.unique(arr,return_counts=True)
  n=max(counts)
  val=unique[counts==n][0]
  print(f'most frequent value is {val}')
  for i in range(len(arr)):
    if arr[i]==val:
      print(i,end="")
  print("")
x=np.array([1,2,3,4,5,1,2,1,1,1])
most_freq(x)
y=np.array([1,1,1,2,3,4,2,4,3,3])
most_freq(y)


[5 4 6 3 2 1]
most frequent value is 1
05789
most frequent value is 1
012


In [ ]:
#Q3
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [ ]:
#Q4
Prannay=np.linspace(10,100,25)
print("Dimension is ",Prannay.ndim)
print("Shape is ",Prannay.shape)
print("Total elements= ",Prannay.size)
print("Data type of each element is ",Prannay.dtype)
print("Total bytes consumed by array are ",Prannay.nbytes)
transpose=Prannay.reshape(-1,1)
print("Transpose using reshape",transpose)
transpose=Prannay.T
print("Transpose using T attribute",transpose)

Dimension is  1
Shape is  (25,)
Total elements=  25
Data type of each element is  float64
Total bytes consumed by array are  200
Transpose using reshape [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
#Q5
ucs420_Prannay=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("mean=",np.mean(ucs420_Prannay))
print("median=",np.median(ucs420_Prannay))
print("max=",np.max(ucs420_Prannay))
print("min=",np.min(ucs420_Prannay))
print("unique elements:",np.unique(ucs420_Prannay))
reshaped_ucs420_Prannay=np.reshape(ucs420_Prannay,(4,3))
print("reshaped array")
print(reshaped_ucs420_Prannay)
resized_ucs420_Prannay=np.resize(ucs420_Prannay,(2,3))
print("resized array")
print(resized_ucs420_Prannay)

mean= 43.333333333333336
median= 37.5
max= 90
min= 10
unique elements: [10 15 20 30 35 40 50 60 70 80 90]
reshaped array
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
resized array
[[10 20 30]
 [40 50 60]]
